<a href="https://colab.research.google.com/github/Paras1719/NNDL-practicals/blob/main/NNDL_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [17]:
A=np.array([[2,3],[5,5]])
B=np.array([[4,6],[2,3]])

print("Matrix Addition:\n", A+B)
print("Matrix Multiplication:\n", np.matmul(A,B))

Matrix Addition:
 [[6 9]
 [7 8]]
Matrix Multiplication:
 [[14 21]
 [30 45]]


In [18]:
C = np.array([[2, 3, 1],
              [5, 5, 2],
              [4, 1, 3]])
D = np.array([[4, 6, 2],
              [2, 3, 7],
              [1, 0, 5]])

print("Matrix Multiplication:\n", np.matmul(C,D))


Matrix Multiplication:
 [[15 21 30]
 [32 45 55]
 [21 27 30]]
